##################
# Authors: Garrett
# Date: Jan. 2018
##################

demo:
	@echo ""
	@echo "--- Tensor Mining using D-Cube ---"

darpa_import:
	psql -d postgres -U postgres -a -f import_darpa_data.sql

compute_dense_blocks:
	